[package]
name = "reproducible"
version = "0.4.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shadow-rs = "0.7"

[build-dependencies]
shadow-rs = "0.7"